### ISSUE TITLE
[MSTAGE-3] The stage plugin only supports copying from http(s) to scp urls

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-stage-plugin#22]
**[Maria Odea B. Ching](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oching)** opened **[MSTAGE-3](https://issues.apache.org/jira/browse/MSTAGE-3?redirect=false)** and commented

---

**Affects:** 1.0-alpha-2

**Attachments:**
- [MSTAGE-3.patch](https://issues.apache.org/jira/secure/attachment/12719584/MSTAGE-3.patch) (_3.04 kB_)

**Issue Links:**
- [MSTAGE-6](https://issues.apache.org/jira/browse/MSTAGE-6) stage:copy fails with Maven 2.0.9
 (_**"is duplicated by"**_)
- [MNG-3581](https://issues.apache.org/jira/browse/MNG-3581) stage:copy ClassCastException with maven 2.0.9

- [MSTAGE-5](https://issues.apache.org/jira/browse/MSTAGE-5) support non-command execution wagons for deployment

- [WAGON-209](https://issues.apache.org/jira/browse/WAGON-209) Extend Wagon API to support the Stage Plugin

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Rahul Akolkar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rahul@apache.org)** commented

I discovered this in trying to move a staged release today.

The attached patch fixes it for me (I used scpexe:// for the target repo, which fails without the patch and succeeds with the patch). The earlier cast to ScpWagon for the lines in question seems overly restrictive and exclusionary.

**Comment by jira-importer** [comment]
**[Conny Kreyßel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=azgard)** commented

This address also my error i gotwhen i try to move from http-repo to a dav-repo.

[INFO] ------------------------------------------------------------------------
[INFO] org.apache.maven.wagon.providers.webdav.WebDavWagon cannot be cast to org.apache.maven.wagon.providers.ssh.jsch.S
cpWagon
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.ClassCastException: org.apache.maven.wagon.providers.webdav.WebDavWagon cannot be cast to org.apache.maven.wag
on.providers.ssh.jsch.ScpWagon
at org.apache.maven.plugins.stage.DefaultRepositoryCopier.copy(DefaultRepositoryCopier.java:252)
at org.apache.maven.plugins.stage.CopyRepositoryMojo.execute(CopyRepositoryMojo.java:93)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

applied, thanks. This only genericises to command executors - opened MSTAGE-5 to make it work with others

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

I'm trying to update the docs for this change, but I'm not sure I understand how wagon works. The patch did not add any new dependencies to the plugin. However, isn't the wagon-ssh-external provider need to use scpexe? Or should that be provided by the project using the plugin?

Regarding what protocols the plugin now supports, am I reading the wagon source correctly if I say the this plugin now supports the following protocols for the target repo?
- scp:
- scpexe:

and also this one, which also extends CommandExecutor

- sftp
