### ISSUE TITLE
[MSTAGE-9] Stage plugin fails with ClassCastException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-stage-plugin#28]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** opened **[MSTAGE-9](https://issues.apache.org/jira/browse/MSTAGE-9?redirect=false)** and commented

[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] org.apache.maven.wagon.providers.ssh.jsch.ScpWagon
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.ClassCastException: org.apache.maven.wagon.providers.ssh.jsch.ScpWagon
at org.apache.maven.plugins.stage.DefaultRepositoryCopier.copy(DefaultRepositoryCopier.java:252)
at org.apache.maven.plugins.stage.CopyRepositoryMojo.execute(CopyRepositoryMojo.java:93)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49 seconds
[INFO] Finished at: Wed Dec 10 22:13:24 EST 2008
[INFO] Final Memory: 3M/6M
[INFO] ------------------------------------------------------------------------
/Users/benson/xmlschema

mvn stage:copy \
-Dsource="http://people.apache.org/~bimargulies/maven_staging" \
-Dtarget="scp://people.apache.org/www/people.apache.org/repo/m2-ibiblio-rsync-repository" \
-Dversion=1.4.3 \
-DtargetRepositoryId=apache.releases

\<servers>
\<server>
\<id>apache-repo\</id>
\<username>bimargulies\</username>
\</server>
\<server>
\<id>apache.releases\</id>
\<username>bimargulies\</username>
\</server>
\<server>
\<id>apache-snapshots\</id>
\<username>bimargulies\</username>
\</server>
\</servers>

---

**Affects:** 1.0-alpha-1

**Issue Links:**
- [MNG-3581](https://issues.apache.org/jira/browse/MNG-3581) stage:copy ClassCastException with maven 2.0.9

**Comment by jira-importer** [comment]
**[Emmanuel Lécharny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elecharny)** commented

Same problem with 1.0-alpha2 :

> MacBookPro:trunk pajbam$ mvn stage:copy -Dsource="http://localhost/~pajbam/ApacheDirectoryStudio-1.5.2.v20091209" -Dtarget="scpexe://people.apache.org/home/pamarcelot/repository" -Dversion=1.5.2.v20091209 -DtargetRepositoryId=aplease -Prelease
> 
>> [INFO] Scanning for projects...
>> [-----SNIP-----]
>> [INFO] Creating zip file.
>> [INFO] Creating rename script.
>> [INFO] Uploading zip file to the target repository.
>> [INFO] Unpacking zip file on the target machine.
>> [INFO] ------------------------------------------------------------------------
>> [ERROR] FATAL ERROR
>> [INFO] ------------------------------------------------------------------------
>> [INFO] org.apache.maven.wagon.providers.ssh.external.ScpExternalWagon cannot be cast to org.apache.maven.wagon.providers.ssh.jsch.ScpWagon
>> [INFO] ------------------------------------------------------------------------
>> [INFO] Trace
>> java.lang.ClassCastException: org.apache.maven.wagon.providers.ssh.external.ScpExternalWagon cannot be cast to org.apache.maven.wagon.providers.ssh.jsch.ScpWagon
>> at org.apache.maven.plugins.stage.DefaultRepositoryCopier.copy(DefaultRepositoryCopier.java:252)
>> at org.apache.maven.plugins.stage.CopyRepositoryMojo.execute(CopyRepositoryMojo.java:93)
>> at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
>> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
>> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
>> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
>> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
>> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)
>> at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
>> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
>> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
>> at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
>> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>> at java.lang.reflect.Method.invoke(Method.java:597)
>> at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
>> at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
>> at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
>> at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
>> [INFO] ------------------------------------------------------------------------
>> [INFO] Total time: 55 minutes 36 seconds
>> [INFO] Finished at: Thu Dec 10 11:38:46 CET 2009
>> [INFO] Final Memory: 22M/80M
>> [INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Due to MNG-3581, be sure to use Maven 2.0.10 or newer.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Fixed in [r1028469](http://svn.apache.org/viewvc?view=revision&revision=1028469), by updating the prerequisite Maven version to 2.0.10.
