### ISSUE TITLE
[MSTAGE-20] No implementation for org.apache.maven.plugins.stage.RepositoryCopier was bound

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-stage-plugin#41]
**[Christian Schulz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cschulz)** opened **[MSTAGE-20](https://issues.apache.org/jira/browse/MSTAGE-20?redirect=false)** and commented

```
mvn org.apache.maven.plugins:maven-stage-plugin:1.0:copy -Dsource=http://localhost:8084/nexus/content/repositories/releases/ -Dtarget=http://localhost:8084/nexus/content/repositories/Test/
```

fails with

```
[INFO] --- maven-stage-plugin:1.0:copy (default-cli) @ standalone-pom ---
[WARNING] Error injecting: org.apache.maven.plugins.stage.CopyRepositoryMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.apache.maven.plugins.stage.RepositoryCopier was bound.
  while locating org.apache.maven.plugins.stage.CopyRepositoryMojo

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:113)
        at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:122)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
        at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:464)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

---

**Remote Links:**
- [GitHub Pull Request #1
](https://github.com/apache/maven-stage-plugin/pull/1)

5 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Christian Schulz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cschulz)** commented

Sehr geehrte Damen und Herren,

meine E-Mailadresse ändert sich zeitnah, bitte speichern Sie meinen Kontakt mit christian@schulz.re ab.

Mit freundlichen Grüßen
-----------------------

<christian.schulz@ewetel.net>

**Comment by jira-importer** [comment]
**[Anders Jacobsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=akj)** commented

I get the same error when using the plugin. It does not make any difference to add the plexus-component-metadata plugin to the pom.xml of the stage-file.

```
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-stage-plugin:1.0:copy from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-stage-plugin:1.0, parent: sun.misc.Launcher$AppClassLoader@1c8825a5]
[WARNING] Error injecting: org.apache.maven.plugins.stage.CopyRepositoryMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.apache.maven.plugins.stage.RepositoryCopier was bound.
  while locating org.apache.maven.plugins.stage.CopyRepositoryMojo

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:36)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:546)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.886 s
[INFO] Finished at: 2016-06-17T10:38:11+02:00
[INFO] Final Memory: 9M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-stage-plugin:1.0:copy (default-cli) on project copy-to-release-repo: Execution default-cli of goal org.apache.maven.plugins:maven-stage-plugin:1.0:copy failed: Unable to load the mojo 'copy' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-stage-plugin:1.0': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) No implementation for org.apache.maven.plugins.stage.RepositoryCopier was bound.
[ERROR] while locating org.apache.maven.plugins.stage.CopyRepositoryMojo
[ERROR] at ClassRealm[plugin>org.apache.maven.plugins:maven-stage-plugin:1.0, parent: sun.misc.Launcher$AppClassLoader@1c8825a5] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.apache.maven.plugins:maven-stage-plugin:1.0:copy)
[ERROR] 
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: org.apache.maven.plugins:maven-stage-plugin:1.0:copy
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-stage-plugin:1.0:copy (default-cli) on project copy-to-release-repo: Execution default-cli of goal org.apache.maven.plugins:maven-stage-plugin:1.0:copy failed: Unable to load the mojo 'copy' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-stage-plugin:1.0'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-stage-plugin:1.0:copy failed: Unable to load the mojo 'copy' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-stage-plugin:1.0'
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'copy' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-stage-plugin:1.0'
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:579)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	... 21 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.apache.maven.plugins.stage.RepositoryCopier was bound.
  while locating org.apache.maven.plugins.stage.CopyRepositoryMojo
  at ClassRealm[plugin>org.apache.maven.plugins:maven-stage-plugin:1.0, parent: sun.misc.Launcher$AppClassLoader@1c8825a5] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.apache.maven.plugins:maven-stage-plugin:1.0:copy)

1 error
      role: org.apache.maven.plugin.Mojo
  roleHint: org.apache.maven.plugins:maven-stage-plugin:1.0:copy
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:546)
	... 22 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.apache.maven.plugins.stage.RepositoryCopier was bound.
  while locating org.apache.maven.plugins.stage.CopyRepositoryMojo
  at ClassRealm[plugin>org.apache.maven.plugins:maven-stage-plugin:1.0, parent: sun.misc.Launcher$AppClassLoader@1c8825a5] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.apache.maven.plugins:maven-stage-plugin:1.0:copy)

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:36)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	... 24 more
```

I'm using Maven 3.3.9

Let me know if I can assist with more information...

Best regards,
Anders Jacobsen

**Comment by jira-importer** [comment]
**[Michael Kühn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkuehn)** commented

Thanks to [Bing Shiao](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bingshiao).

[Anders Jacobsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=akj) You must define the plexus-component-metadata plugin in **pom.xml of the maven-stage-plugin**, build the plugin and put it into your repository.

Best regards
Michael

**Comment by jira-importer** [comment]
**[Mirko Raner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mirko@raner.ws)** commented

Same problem here when running on Maven 3.5.2 :(
